### ISSUE TITLE
Iggy

### ISSUE THREAD

**Issue by giovannicarlino04** [r-lyeh/statvs#1]
https://github.com/r-lyeh-archived/spot/issues/2
Based on this, correct me if I'm wrong, you developed IGGY for RAD GAME TOOLS. Since I don't think you can share the tool due to copyright reasons (besides, I'd never ask you to do that) Would you mind giving me some info about iggy file format? I am currently trying to develop a tool to make Iggy File editing easier

**Comment by r-lyeh** [comment]
that snippet is from @nothings; you could either ping him or ping rad tools directly about Iggy

**Comment by giovannicarlino04** [comment]
Oh alright, thank you.

Il sab 17 feb 2024, 19:30 r-lyeh ***@***.***> ha scritto:
